// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetPeriodParams is parameters of getPeriod operation.
type GetPeriodParams struct {
	PeriodId uuid.UUID
}

func unpackGetPeriodParams(packed middleware.Parameters) (params GetPeriodParams) {
	{
		key := middleware.ParameterKey{
			Name: "periodId",
			In:   "path",
		}
		params.PeriodId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetPeriodParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPeriodParams, _ error) {
	// Decode path: periodId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "periodId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PeriodId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "periodId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTransactionParams is parameters of getTransaction operation.
type GetTransactionParams struct {
	TransactionId uuid.UUID
}

func unpackGetTransactionParams(packed middleware.Parameters) (params GetTransactionParams) {
	{
		key := middleware.ParameterKey{
			Name: "transactionId",
			In:   "path",
		}
		params.TransactionId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetTransactionParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTransactionParams, _ error) {
	// Decode path: transactionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "transactionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TransactionId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "transactionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListAllocationsParams is parameters of listAllocations operation.
type ListAllocationsParams struct {
	// The financial period to inspect.
	PeriodId uuid.UUID
	// Filter by specific user (defaults to all users if omitted).
	UserId OptUUID `json:",omitempty,omitzero"`
}

func unpackListAllocationsParams(packed middleware.Parameters) (params ListAllocationsParams) {
	{
		key := middleware.ParameterKey{
			Name: "periodId",
			In:   "query",
		}
		params.PeriodId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "userId",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.UserId = v.(OptUUID)
		}
	}
	return params
}

func decodeListAllocationsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListAllocationsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: periodId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "periodId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PeriodId = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "periodId",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: userId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "userId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUserIdVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotUserIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.UserId.SetTo(paramsDotUserIdVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userId",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListTransactionsParams is parameters of listTransactions operation.
type ListTransactionsParams struct {
	// Filter by period.
	PeriodId OptUUID `json:",omitempty,omitzero"`
}

func unpackListTransactionsParams(packed middleware.Parameters) (params ListTransactionsParams) {
	{
		key := middleware.ParameterKey{
			Name: "periodId",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.PeriodId = v.(OptUUID)
		}
	}
	return params
}

func decodeListTransactionsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListTransactionsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: periodId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "periodId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPeriodIdVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotPeriodIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.PeriodId.SetTo(paramsDotPeriodIdVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "periodId",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
