// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTransaction implements createTransaction operation.
//
// Create a new transaction.
//
// POST /transactions
func (UnimplementedHandler) CreateTransaction(ctx context.Context, req *CreateTransaction) (r CreateTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentPeriod implements getCurrentPeriod operation.
//
// Get current active period.
//
// GET /periods/current
func (UnimplementedHandler) GetCurrentPeriod(ctx context.Context) (r *Period, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentUser implements getCurrentUser operation.
//
// Get current authenticated user.
//
// GET /me
func (UnimplementedHandler) GetCurrentUser(ctx context.Context) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPeriod implements getPeriod operation.
//
// Get period by ID.
//
// GET /periods/{periodId}
func (UnimplementedHandler) GetPeriod(ctx context.Context, params GetPeriodParams) (r GetPeriodRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTransaction implements getTransaction operation.
//
// Get transaction by ID.
//
// GET /transactions/{transactionId}
func (UnimplementedHandler) GetTransaction(ctx context.Context, params GetTransactionParams) (r GetTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPeriods implements listPeriods operation.
//
// List all financial periods.
//
// GET /periods
func (UnimplementedHandler) ListPeriods(ctx context.Context) (r []PeriodListItem, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTransactions implements listTransactions operation.
//
// List transactions.
//
// GET /transactions
func (UnimplementedHandler) ListTransactions(ctx context.Context, params ListTransactionsParams) (r []Transaction, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements listUsers operation.
//
// List all household users.
//
// GET /users
func (UnimplementedHandler) ListUsers(ctx context.Context) (r []User, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
