// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Allocation
type Allocation struct {
	ID       uuid.UUID         `json:"id"`
	PeriodId uuid.UUID         `json:"periodId"`
	UserId   uuid.UUID         `json:"userId"`
	Purpose  AllocationPurpose `json:"purpose"`
	// Allocated amount in para (1/100 RSD).
	Amount int64 `json:"amount"`
	// Amount spent in para (1/100 RSD).
	Spent int64 `json:"spent"`
	// Remaining amount in para (1/100 RSD).
	Remaining int64 `json:"remaining"`
}

// GetID returns the value of ID.
func (s *Allocation) GetID() uuid.UUID {
	return s.ID
}

// GetPeriodId returns the value of PeriodId.
func (s *Allocation) GetPeriodId() uuid.UUID {
	return s.PeriodId
}

// GetUserId returns the value of UserId.
func (s *Allocation) GetUserId() uuid.UUID {
	return s.UserId
}

// GetPurpose returns the value of Purpose.
func (s *Allocation) GetPurpose() AllocationPurpose {
	return s.Purpose
}

// GetAmount returns the value of Amount.
func (s *Allocation) GetAmount() int64 {
	return s.Amount
}

// GetSpent returns the value of Spent.
func (s *Allocation) GetSpent() int64 {
	return s.Spent
}

// GetRemaining returns the value of Remaining.
func (s *Allocation) GetRemaining() int64 {
	return s.Remaining
}

// SetID sets the value of ID.
func (s *Allocation) SetID(val uuid.UUID) {
	s.ID = val
}

// SetPeriodId sets the value of PeriodId.
func (s *Allocation) SetPeriodId(val uuid.UUID) {
	s.PeriodId = val
}

// SetUserId sets the value of UserId.
func (s *Allocation) SetUserId(val uuid.UUID) {
	s.UserId = val
}

// SetPurpose sets the value of Purpose.
func (s *Allocation) SetPurpose(val AllocationPurpose) {
	s.Purpose = val
}

// SetAmount sets the value of Amount.
func (s *Allocation) SetAmount(val int64) {
	s.Amount = val
}

// SetSpent sets the value of Spent.
func (s *Allocation) SetSpent(val int64) {
	s.Spent = val
}

// SetRemaining sets the value of Remaining.
func (s *Allocation) SetRemaining(val int64) {
	s.Remaining = val
}

type AllocationPurpose string

const (
	AllocationPurposeGroceries    AllocationPurpose = "groceries"
	AllocationPurposeHousekeeping AllocationPurpose = "housekeeping"
	AllocationPurposePersonal     AllocationPurpose = "personal"
)

// AllValues returns all AllocationPurpose values.
func (AllocationPurpose) AllValues() []AllocationPurpose {
	return []AllocationPurpose{
		AllocationPurposeGroceries,
		AllocationPurposeHousekeeping,
		AllocationPurposePersonal,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AllocationPurpose) MarshalText() ([]byte, error) {
	switch s {
	case AllocationPurposeGroceries:
		return []byte(s), nil
	case AllocationPurposeHousekeeping:
		return []byte(s), nil
	case AllocationPurposePersonal:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AllocationPurpose) UnmarshalText(data []byte) error {
	switch AllocationPurpose(data) {
	case AllocationPurposeGroceries:
		*s = AllocationPurposeGroceries
		return nil
	case AllocationPurposeHousekeeping:
		*s = AllocationPurposeHousekeeping
		return nil
	case AllocationPurposePersonal:
		*s = AllocationPurposePersonal
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/CreateTransaction
type CreateTransaction struct {
	AllocationId uuid.UUID `json:"allocationId"`
	// Transaction amount in para (1/100 RSD).
	Amount      int64     `json:"amount"`
	Description OptString `json:"description"`
	Category    OptString `json:"category"`
}

// GetAllocationId returns the value of AllocationId.
func (s *CreateTransaction) GetAllocationId() uuid.UUID {
	return s.AllocationId
}

// GetAmount returns the value of Amount.
func (s *CreateTransaction) GetAmount() int64 {
	return s.Amount
}

// GetDescription returns the value of Description.
func (s *CreateTransaction) GetDescription() OptString {
	return s.Description
}

// GetCategory returns the value of Category.
func (s *CreateTransaction) GetCategory() OptString {
	return s.Category
}

// SetAllocationId sets the value of AllocationId.
func (s *CreateTransaction) SetAllocationId(val uuid.UUID) {
	s.AllocationId = val
}

// SetAmount sets the value of Amount.
func (s *CreateTransaction) SetAmount(val int64) {
	s.Amount = val
}

// SetDescription sets the value of Description.
func (s *CreateTransaction) SetDescription(val OptString) {
	s.Description = val
}

// SetCategory sets the value of Category.
func (s *CreateTransaction) SetCategory(val OptString) {
	s.Category = val
}

// CreateTransactionBadRequest is response for CreateTransaction operation.
type CreateTransactionBadRequest struct{}

func (*CreateTransactionBadRequest) createTransactionRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// GetPeriodNotFound is response for GetPeriod operation.
type GetPeriodNotFound struct{}

func (*GetPeriodNotFound) getPeriodRes() {}

// GetTransactionNotFound is response for GetTransaction operation.
type GetTransactionNotFound struct{}

func (*GetTransactionNotFound) getTransactionRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Period
type Period struct {
	ID        uuid.UUID `json:"id"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
	IsActive  bool      `json:"isActive"`
	// Total household budget.
	TotalBudget int64 `json:"totalBudget"`
	// Last known remaining balance.
	LastKnownRemain int64 `json:"lastKnownRemain"`
	// Total spendings for the period.
	TotalSpent  int64        `json:"totalSpent"`
	Allocations []Allocation `json:"allocations"`
}

// GetID returns the value of ID.
func (s *Period) GetID() uuid.UUID {
	return s.ID
}

// GetStartDate returns the value of StartDate.
func (s *Period) GetStartDate() time.Time {
	return s.StartDate
}

// GetEndDate returns the value of EndDate.
func (s *Period) GetEndDate() time.Time {
	return s.EndDate
}

// GetIsActive returns the value of IsActive.
func (s *Period) GetIsActive() bool {
	return s.IsActive
}

// GetTotalBudget returns the value of TotalBudget.
func (s *Period) GetTotalBudget() int64 {
	return s.TotalBudget
}

// GetLastKnownRemain returns the value of LastKnownRemain.
func (s *Period) GetLastKnownRemain() int64 {
	return s.LastKnownRemain
}

// GetTotalSpent returns the value of TotalSpent.
func (s *Period) GetTotalSpent() int64 {
	return s.TotalSpent
}

// GetAllocations returns the value of Allocations.
func (s *Period) GetAllocations() []Allocation {
	return s.Allocations
}

// SetID sets the value of ID.
func (s *Period) SetID(val uuid.UUID) {
	s.ID = val
}

// SetStartDate sets the value of StartDate.
func (s *Period) SetStartDate(val time.Time) {
	s.StartDate = val
}

// SetEndDate sets the value of EndDate.
func (s *Period) SetEndDate(val time.Time) {
	s.EndDate = val
}

// SetIsActive sets the value of IsActive.
func (s *Period) SetIsActive(val bool) {
	s.IsActive = val
}

// SetTotalBudget sets the value of TotalBudget.
func (s *Period) SetTotalBudget(val int64) {
	s.TotalBudget = val
}

// SetLastKnownRemain sets the value of LastKnownRemain.
func (s *Period) SetLastKnownRemain(val int64) {
	s.LastKnownRemain = val
}

// SetTotalSpent sets the value of TotalSpent.
func (s *Period) SetTotalSpent(val int64) {
	s.TotalSpent = val
}

// SetAllocations sets the value of Allocations.
func (s *Period) SetAllocations(val []Allocation) {
	s.Allocations = val
}

func (*Period) getPeriodRes() {}

// Ref: #/components/schemas/Transaction
type Transaction struct {
	ID           uuid.UUID `json:"id"`
	PeriodId     uuid.UUID `json:"periodId"`
	UserId       uuid.UUID `json:"userId"`
	AllocationId uuid.UUID `json:"allocationId"`
	// Transaction amount in para (1/100 RSD).
	Amount      int64     `json:"amount"`
	Description OptString `json:"description"`
	Date        time.Time `json:"date"`
	Category    OptString `json:"category"`
}

// GetID returns the value of ID.
func (s *Transaction) GetID() uuid.UUID {
	return s.ID
}

// GetPeriodId returns the value of PeriodId.
func (s *Transaction) GetPeriodId() uuid.UUID {
	return s.PeriodId
}

// GetUserId returns the value of UserId.
func (s *Transaction) GetUserId() uuid.UUID {
	return s.UserId
}

// GetAllocationId returns the value of AllocationId.
func (s *Transaction) GetAllocationId() uuid.UUID {
	return s.AllocationId
}

// GetAmount returns the value of Amount.
func (s *Transaction) GetAmount() int64 {
	return s.Amount
}

// GetDescription returns the value of Description.
func (s *Transaction) GetDescription() OptString {
	return s.Description
}

// GetDate returns the value of Date.
func (s *Transaction) GetDate() time.Time {
	return s.Date
}

// GetCategory returns the value of Category.
func (s *Transaction) GetCategory() OptString {
	return s.Category
}

// SetID sets the value of ID.
func (s *Transaction) SetID(val uuid.UUID) {
	s.ID = val
}

// SetPeriodId sets the value of PeriodId.
func (s *Transaction) SetPeriodId(val uuid.UUID) {
	s.PeriodId = val
}

// SetUserId sets the value of UserId.
func (s *Transaction) SetUserId(val uuid.UUID) {
	s.UserId = val
}

// SetAllocationId sets the value of AllocationId.
func (s *Transaction) SetAllocationId(val uuid.UUID) {
	s.AllocationId = val
}

// SetAmount sets the value of Amount.
func (s *Transaction) SetAmount(val int64) {
	s.Amount = val
}

// SetDescription sets the value of Description.
func (s *Transaction) SetDescription(val OptString) {
	s.Description = val
}

// SetDate sets the value of Date.
func (s *Transaction) SetDate(val time.Time) {
	s.Date = val
}

// SetCategory sets the value of Category.
func (s *Transaction) SetCategory(val OptString) {
	s.Category = val
}

func (*Transaction) createTransactionRes() {}
func (*Transaction) getTransactionRes()    {}

// Ref: #/components/schemas/User
type User struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	// Remaining balance for current period in para (1/100 RSD).
	CurrentBalance int64 `json:"currentBalance"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetCurrentBalance returns the value of CurrentBalance.
func (s *User) GetCurrentBalance() int64 {
	return s.CurrentBalance
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetCurrentBalance sets the value of CurrentBalance.
func (s *User) SetCurrentBalance(val int64) {
	s.CurrentBalance = val
}
