// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateEnvelopeOperation    OperationName = "CreateEnvelope"
	CreatePeriodOperation      OperationName = "CreatePeriod"
	CreateTransactionOperation OperationName = "CreateTransaction"
	DeleteEnvelopeOperation    OperationName = "DeleteEnvelope"
	DeletePeriodOperation      OperationName = "DeletePeriod"
	DeleteTransactionOperation OperationName = "DeleteTransaction"
	GetCurrentPeriodOperation  OperationName = "GetCurrentPeriod"
	GetCurrentUserOperation    OperationName = "GetCurrentUser"
	GetEnvelopeOperation       OperationName = "GetEnvelope"
	GetPeriodOperation         OperationName = "GetPeriod"
	GetTransactionOperation    OperationName = "GetTransaction"
	ListEnvelopesOperation     OperationName = "ListEnvelopes"
	ListPeriodsOperation       OperationName = "ListPeriods"
	ListTransactionsOperation  OperationName = "ListTransactions"
	ListUsersOperation         OperationName = "ListUsers"
	UpdateEnvelopeOperation    OperationName = "UpdateEnvelope"
	UpdatePeriodOperation      OperationName = "UpdatePeriod"
	UpdateTransactionOperation OperationName = "UpdateTransaction"
)
