// Code generated by ogen, DO NOT EDIT.
package oas

type CreateTransactionRes interface {
	createTransactionRes()
}

type GetPeriodRes interface {
	getPeriodRes()
}

type GetTransactionRes interface {
	getTransactionRes()
}
