// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateEnvelope implements createEnvelope operation.
//
// Create a new envelope.
//
// POST /envelopes
func (UnimplementedHandler) CreateEnvelope(ctx context.Context, req *CreateEnvelope) (r *Envelope, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePeriod implements createPeriod operation.
//
// Create a new financial period.
//
// POST /periods
func (UnimplementedHandler) CreatePeriod(ctx context.Context, req *CreatePeriod) (r *PeriodSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTransaction implements createTransaction operation.
//
// Create a new transaction.
//
// POST /transactions
func (UnimplementedHandler) CreateTransaction(ctx context.Context, req *CreateTransaction) (r CreateTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEnvelope implements deleteEnvelope operation.
//
// Delete an envelope.
//
// DELETE /envelopes/{envelopeId}
func (UnimplementedHandler) DeleteEnvelope(ctx context.Context, params DeleteEnvelopeParams) (r DeleteEnvelopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePeriod implements deletePeriod operation.
//
// Delete a period.
//
// DELETE /periods/{periodId}
func (UnimplementedHandler) DeletePeriod(ctx context.Context, params DeletePeriodParams) (r DeletePeriodRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTransaction implements deleteTransaction operation.
//
// Delete a transaction.
//
// DELETE /transactions/{transactionId}
func (UnimplementedHandler) DeleteTransaction(ctx context.Context, params DeleteTransactionParams) (r DeleteTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentPeriod implements getCurrentPeriod operation.
//
// Get current active period.
//
// GET /periods/current
func (UnimplementedHandler) GetCurrentPeriod(ctx context.Context) (r *PeriodSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentUser implements getCurrentUser operation.
//
// Get current authenticated user.
//
// GET /me
func (UnimplementedHandler) GetCurrentUser(ctx context.Context) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvelope implements getEnvelope operation.
//
// Get envelope by ID.
//
// GET /envelopes/{envelopeId}
func (UnimplementedHandler) GetEnvelope(ctx context.Context, params GetEnvelopeParams) (r GetEnvelopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPeriod implements getPeriod operation.
//
// Get period by ID.
//
// GET /periods/{periodId}
func (UnimplementedHandler) GetPeriod(ctx context.Context, params GetPeriodParams) (r GetPeriodRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTransaction implements getTransaction operation.
//
// Get transaction by ID.
//
// GET /transactions/{transactionId}
func (UnimplementedHandler) GetTransaction(ctx context.Context, params GetTransactionParams) (r GetTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListEnvelopes implements listEnvelopes operation.
//
// List all envelopes.
//
// GET /envelopes
func (UnimplementedHandler) ListEnvelopes(ctx context.Context) (r []Envelope, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPeriods implements listPeriods operation.
//
// List all financial periods.
//
// GET /periods
func (UnimplementedHandler) ListPeriods(ctx context.Context) (r []PeriodListItem, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTransactions implements listTransactions operation.
//
// List transactions.
//
// GET /transactions
func (UnimplementedHandler) ListTransactions(ctx context.Context, params ListTransactionsParams) (r []Transaction, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements listUsers operation.
//
// List all household users.
//
// GET /users
func (UnimplementedHandler) ListUsers(ctx context.Context) (r []User, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEnvelope implements updateEnvelope operation.
//
// Update an envelope.
//
// PATCH /envelopes/{envelopeId}
func (UnimplementedHandler) UpdateEnvelope(ctx context.Context, req *UpdateEnvelope, params UpdateEnvelopeParams) (r UpdateEnvelopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePeriod implements updatePeriod operation.
//
// Update a period.
//
// PATCH /periods/{periodId}
func (UnimplementedHandler) UpdatePeriod(ctx context.Context, req *UpdatePeriod, params UpdatePeriodParams) (r UpdatePeriodRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTransaction implements updateTransaction operation.
//
// Update a transaction.
//
// PATCH /transactions/{transactionId}
func (UnimplementedHandler) UpdateTransaction(ctx context.Context, req *UpdateTransaction, params UpdateTransactionParams) (r UpdateTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
