// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateTransactionOperation OperationName = "CreateTransaction"
	GetCurrentPeriodOperation  OperationName = "GetCurrentPeriod"
	GetCurrentUserOperation    OperationName = "GetCurrentUser"
	GetPeriodOperation         OperationName = "GetPeriod"
	GetTransactionOperation    OperationName = "GetTransaction"
	ListPeriodsOperation       OperationName = "ListPeriods"
	ListTransactionsOperation  OperationName = "ListTransactions"
	ListUsersOperation         OperationName = "ListUsers"
)
