// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/CreateTransaction
type CreateTransaction struct {
	// The budget bucket this transaction belongs to.
	EnvelopeId uuid.UUID `json:"envelopeId"`
	// Transaction amount in currency cents. Use negative values for expenses.
	Amount      int64     `json:"amount"`
	Description OptString `json:"description"`
	// Analytics tag (what was bought).
	Category OptString `json:"category"`
}

// GetEnvelopeId returns the value of EnvelopeId.
func (s *CreateTransaction) GetEnvelopeId() uuid.UUID {
	return s.EnvelopeId
}

// GetAmount returns the value of Amount.
func (s *CreateTransaction) GetAmount() int64 {
	return s.Amount
}

// GetDescription returns the value of Description.
func (s *CreateTransaction) GetDescription() OptString {
	return s.Description
}

// GetCategory returns the value of Category.
func (s *CreateTransaction) GetCategory() OptString {
	return s.Category
}

// SetEnvelopeId sets the value of EnvelopeId.
func (s *CreateTransaction) SetEnvelopeId(val uuid.UUID) {
	s.EnvelopeId = val
}

// SetAmount sets the value of Amount.
func (s *CreateTransaction) SetAmount(val int64) {
	s.Amount = val
}

// SetDescription sets the value of Description.
func (s *CreateTransaction) SetDescription(val OptString) {
	s.Description = val
}

// SetCategory sets the value of Category.
func (s *CreateTransaction) SetCategory(val OptString) {
	s.Category = val
}

// CreateTransactionBadRequest is response for CreateTransaction operation.
type CreateTransactionBadRequest struct{}

func (*CreateTransactionBadRequest) createTransactionRes() {}

// Ref: #/components/schemas/EnvelopeSummary
type EnvelopeSummary struct {
	UserId uuid.UUID `json:"userId"`
	// The ID of the budget bucket.
	EnvelopeId uuid.UUID `json:"envelopeId"`
	// The name of the budget bucket (e.g., 'groceries').
	Envelope string `json:"envelope"`
	// Total funding allocated to this envelope in cents.
	Amount int64 `json:"amount"`
	// Total amount spent from this envelope in cents.
	Spent int64 `json:"spent"`
	// Current balance of the envelope in cents.
	Remaining int64 `json:"remaining"`
}

// GetUserId returns the value of UserId.
func (s *EnvelopeSummary) GetUserId() uuid.UUID {
	return s.UserId
}

// GetEnvelopeId returns the value of EnvelopeId.
func (s *EnvelopeSummary) GetEnvelopeId() uuid.UUID {
	return s.EnvelopeId
}

// GetEnvelope returns the value of Envelope.
func (s *EnvelopeSummary) GetEnvelope() string {
	return s.Envelope
}

// GetAmount returns the value of Amount.
func (s *EnvelopeSummary) GetAmount() int64 {
	return s.Amount
}

// GetSpent returns the value of Spent.
func (s *EnvelopeSummary) GetSpent() int64 {
	return s.Spent
}

// GetRemaining returns the value of Remaining.
func (s *EnvelopeSummary) GetRemaining() int64 {
	return s.Remaining
}

// SetUserId sets the value of UserId.
func (s *EnvelopeSummary) SetUserId(val uuid.UUID) {
	s.UserId = val
}

// SetEnvelopeId sets the value of EnvelopeId.
func (s *EnvelopeSummary) SetEnvelopeId(val uuid.UUID) {
	s.EnvelopeId = val
}

// SetEnvelope sets the value of Envelope.
func (s *EnvelopeSummary) SetEnvelope(val string) {
	s.Envelope = val
}

// SetAmount sets the value of Amount.
func (s *EnvelopeSummary) SetAmount(val int64) {
	s.Amount = val
}

// SetSpent sets the value of Spent.
func (s *EnvelopeSummary) SetSpent(val int64) {
	s.Spent = val
}

// SetRemaining sets the value of Remaining.
func (s *EnvelopeSummary) SetRemaining(val int64) {
	s.Remaining = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// GetPeriodNotFound is response for GetPeriod operation.
type GetPeriodNotFound struct{}

func (*GetPeriodNotFound) getPeriodRes() {}

// GetTransactionNotFound is response for GetTransaction operation.
type GetTransactionNotFound struct{}

func (*GetTransactionNotFound) getTransactionRes() {}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Period
type Period struct {
	ID        uuid.UUID `json:"id"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
	IsActive  bool      `json:"isActive"`
	// Total household budget in currency cents.
	TotalBudget int64 `json:"totalBudget"`
	// Last known remaining balance in currency cents.
	TotalRemaining int64 `json:"totalRemaining"`
	// Total spendings for the period in currency cents.
	TotalSpent int64 `json:"totalSpent"`
	// Projected balance at the end of the period in currency cents.
	ProjectedEndingBalance OptInt64          `json:"projectedEndingBalance"`
	EnvelopeSummaries      []EnvelopeSummary `json:"envelopeSummaries"`
}

// GetID returns the value of ID.
func (s *Period) GetID() uuid.UUID {
	return s.ID
}

// GetStartDate returns the value of StartDate.
func (s *Period) GetStartDate() time.Time {
	return s.StartDate
}

// GetEndDate returns the value of EndDate.
func (s *Period) GetEndDate() time.Time {
	return s.EndDate
}

// GetIsActive returns the value of IsActive.
func (s *Period) GetIsActive() bool {
	return s.IsActive
}

// GetTotalBudget returns the value of TotalBudget.
func (s *Period) GetTotalBudget() int64 {
	return s.TotalBudget
}

// GetTotalRemaining returns the value of TotalRemaining.
func (s *Period) GetTotalRemaining() int64 {
	return s.TotalRemaining
}

// GetTotalSpent returns the value of TotalSpent.
func (s *Period) GetTotalSpent() int64 {
	return s.TotalSpent
}

// GetProjectedEndingBalance returns the value of ProjectedEndingBalance.
func (s *Period) GetProjectedEndingBalance() OptInt64 {
	return s.ProjectedEndingBalance
}

// GetEnvelopeSummaries returns the value of EnvelopeSummaries.
func (s *Period) GetEnvelopeSummaries() []EnvelopeSummary {
	return s.EnvelopeSummaries
}

// SetID sets the value of ID.
func (s *Period) SetID(val uuid.UUID) {
	s.ID = val
}

// SetStartDate sets the value of StartDate.
func (s *Period) SetStartDate(val time.Time) {
	s.StartDate = val
}

// SetEndDate sets the value of EndDate.
func (s *Period) SetEndDate(val time.Time) {
	s.EndDate = val
}

// SetIsActive sets the value of IsActive.
func (s *Period) SetIsActive(val bool) {
	s.IsActive = val
}

// SetTotalBudget sets the value of TotalBudget.
func (s *Period) SetTotalBudget(val int64) {
	s.TotalBudget = val
}

// SetTotalRemaining sets the value of TotalRemaining.
func (s *Period) SetTotalRemaining(val int64) {
	s.TotalRemaining = val
}

// SetTotalSpent sets the value of TotalSpent.
func (s *Period) SetTotalSpent(val int64) {
	s.TotalSpent = val
}

// SetProjectedEndingBalance sets the value of ProjectedEndingBalance.
func (s *Period) SetProjectedEndingBalance(val OptInt64) {
	s.ProjectedEndingBalance = val
}

// SetEnvelopeSummaries sets the value of EnvelopeSummaries.
func (s *Period) SetEnvelopeSummaries(val []EnvelopeSummary) {
	s.EnvelopeSummaries = val
}

func (*Period) getPeriodRes() {}

// Ref: #/components/schemas/PeriodListItem
type PeriodListItem struct {
	ID        uuid.UUID `json:"id"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
	IsActive  bool      `json:"isActive"`
}

// GetID returns the value of ID.
func (s *PeriodListItem) GetID() uuid.UUID {
	return s.ID
}

// GetStartDate returns the value of StartDate.
func (s *PeriodListItem) GetStartDate() time.Time {
	return s.StartDate
}

// GetEndDate returns the value of EndDate.
func (s *PeriodListItem) GetEndDate() time.Time {
	return s.EndDate
}

// GetIsActive returns the value of IsActive.
func (s *PeriodListItem) GetIsActive() bool {
	return s.IsActive
}

// SetID sets the value of ID.
func (s *PeriodListItem) SetID(val uuid.UUID) {
	s.ID = val
}

// SetStartDate sets the value of StartDate.
func (s *PeriodListItem) SetStartDate(val time.Time) {
	s.StartDate = val
}

// SetEndDate sets the value of EndDate.
func (s *PeriodListItem) SetEndDate(val time.Time) {
	s.EndDate = val
}

// SetIsActive sets the value of IsActive.
func (s *PeriodListItem) SetIsActive(val bool) {
	s.IsActive = val
}

// Ref: #/components/schemas/Transaction
type Transaction struct {
	ID       uuid.UUID `json:"id"`
	PeriodId uuid.UUID `json:"periodId"`
	UserId   uuid.UUID `json:"userId"`
	// The budget bucket this transaction belongs to.
	EnvelopeId uuid.UUID `json:"envelopeId"`
	// Transaction amount in currency cents. Positive for income/funding, negative for expenses.
	Amount      int64     `json:"amount"`
	Description OptString `json:"description"`
	Date        time.Time `json:"date"`
	// Analytics tag (what was bought).
	Category OptString `json:"category"`
}

// GetID returns the value of ID.
func (s *Transaction) GetID() uuid.UUID {
	return s.ID
}

// GetPeriodId returns the value of PeriodId.
func (s *Transaction) GetPeriodId() uuid.UUID {
	return s.PeriodId
}

// GetUserId returns the value of UserId.
func (s *Transaction) GetUserId() uuid.UUID {
	return s.UserId
}

// GetEnvelopeId returns the value of EnvelopeId.
func (s *Transaction) GetEnvelopeId() uuid.UUID {
	return s.EnvelopeId
}

// GetAmount returns the value of Amount.
func (s *Transaction) GetAmount() int64 {
	return s.Amount
}

// GetDescription returns the value of Description.
func (s *Transaction) GetDescription() OptString {
	return s.Description
}

// GetDate returns the value of Date.
func (s *Transaction) GetDate() time.Time {
	return s.Date
}

// GetCategory returns the value of Category.
func (s *Transaction) GetCategory() OptString {
	return s.Category
}

// SetID sets the value of ID.
func (s *Transaction) SetID(val uuid.UUID) {
	s.ID = val
}

// SetPeriodId sets the value of PeriodId.
func (s *Transaction) SetPeriodId(val uuid.UUID) {
	s.PeriodId = val
}

// SetUserId sets the value of UserId.
func (s *Transaction) SetUserId(val uuid.UUID) {
	s.UserId = val
}

// SetEnvelopeId sets the value of EnvelopeId.
func (s *Transaction) SetEnvelopeId(val uuid.UUID) {
	s.EnvelopeId = val
}

// SetAmount sets the value of Amount.
func (s *Transaction) SetAmount(val int64) {
	s.Amount = val
}

// SetDescription sets the value of Description.
func (s *Transaction) SetDescription(val OptString) {
	s.Description = val
}

// SetDate sets the value of Date.
func (s *Transaction) SetDate(val time.Time) {
	s.Date = val
}

// SetCategory sets the value of Category.
func (s *Transaction) SetCategory(val OptString) {
	s.Category = val
}

func (*Transaction) createTransactionRes() {}
func (*Transaction) getTransactionRes()    {}

// Ref: #/components/schemas/User
type User struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	// Remaining balance for current period in currency cents.
	CurrentBalance int64 `json:"currentBalance"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetCurrentBalance returns the value of CurrentBalance.
func (s *User) GetCurrentBalance() int64 {
	return s.CurrentBalance
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetCurrentBalance sets the value of CurrentBalance.
func (s *User) SetCurrentBalance(val int64) {
	s.CurrentBalance = val
}
