// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateTransaction implements createTransaction operation.
	//
	// Create a new transaction.
	//
	// POST /transactions
	CreateTransaction(ctx context.Context, req *CreateTransaction) (CreateTransactionRes, error)
	// GetCurrentPeriod implements getCurrentPeriod operation.
	//
	// Get current active period.
	//
	// GET /periods/current
	GetCurrentPeriod(ctx context.Context) (*Period, error)
	// GetCurrentUser implements getCurrentUser operation.
	//
	// Get current authenticated user.
	//
	// GET /me
	GetCurrentUser(ctx context.Context) (*User, error)
	// GetCurrentUserAllocations implements getCurrentUserAllocations operation.
	//
	// Get current user's allocation for current period.
	//
	// GET /me/allocations
	GetCurrentUserAllocations(ctx context.Context) ([]Allocation, error)
	// GetPeriod implements getPeriod operation.
	//
	// Get period by ID.
	//
	// GET /periods/{periodId}
	GetPeriod(ctx context.Context, params GetPeriodParams) (GetPeriodRes, error)
	// GetTransaction implements getTransaction operation.
	//
	// Get transaction by ID.
	//
	// GET /transactions/{transactionId}
	GetTransaction(ctx context.Context, params GetTransactionParams) (GetTransactionRes, error)
	// ListPeriods implements listPeriods operation.
	//
	// List all financial periods.
	//
	// GET /periods
	ListPeriods(ctx context.Context) ([]Period, error)
	// ListTransactions implements listTransactions operation.
	//
	// List transactions.
	//
	// GET /transactions
	ListTransactions(ctx context.Context, params ListTransactionsParams) ([]Transaction, error)
	// ListUsers implements listUsers operation.
	//
	// List all household users.
	//
	// GET /users
	ListUsers(ctx context.Context) ([]User, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
